# Generated by Django 3.0.7 on 2020-09-27 11:34

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_description', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('categoryStatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Available', 'Available')], max_length=30, null=True)),
                ('categoryCreated', models.DateTimeField(auto_now_add=True)),
                ('seo_keywords', models.CharField(max_length=160)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(blank=True, max_length=400, null=True)),
                ('courseDescription', models.TextField(blank=True, null=True)),
                ('courseOnline', models.BooleanField(blank=True, default=False, null=True)),
                ('courseImage', models.FileField(blank=True, null=True, upload_to='images/')),
                ('courseLive', models.BooleanField(blank=True, default=False, null=True)),
                ('courseOffline', models.BooleanField(blank=True, default=False, null=True)),
                ('courseStatus', models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Available', 'Available')], max_length=30, null=True)),
                ('coursePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promocode', models.CharField(blank=True, max_length=160, null=True)),
                ('priceDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalPriceDiscount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('courseCity', models.CharField(blank=True, max_length=200, null=True)),
                ('courseState', models.CharField(blank=True, max_length=200, null=True)),
                ('courseCountry', models.CharField(blank=True, max_length=200, null=True)),
                ('offlineAddress', models.TextField(blank=True, null=True)),
                ('offlineClassStrength', models.IntegerField(blank=True, null=True)),
                ('offlineTiming', models.DateTimeField(blank=True, null=True)),
                ('offlineWeekday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True)),
                ('onlineWeekday', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True)),
                ('onlineTiming', models.DateTimeField(blank=True, null=True)),
                ('courseBelong', models.CharField(blank=True, choices=[('Trainer', 'Trainer'), ('Intitute', 'Institute'), ('Franchise', 'Franchise')], max_length=30, null=True)),
                ('seo_title', models.CharField(max_length=70)),
                ('seo_description', models.CharField(max_length=160)),
                ('seo_keywords', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('introVideo', models.FileField(blank=True, null=True, upload_to='IntroVideos/')),
                ('courseCreated', models.DateTimeField(auto_now_add=True)),
                ('courseCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.Categories')),
            ],
            options={
                'ordering': ['-courseCreated'],
            },
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseVideoName', models.CharField(blank=True, max_length=500, null=True)),
                ('courseVideoFile', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('courseVideoDescription', models.TextField(blank=True, null=True)),
                ('courseVideoCreated', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.CourseDetails')),
            ],
        ),
    ]
